// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiEncountersByEncounterIdStateData, GetApiEncountersByEncounterIdStateErrors, GetApiEncountersByEncounterIdStateResponses, PostApiEncountersByEncounterIdCombatantsData, PostApiEncountersByEncounterIdCombatantsResponses, PostApiEncountersData, PostApiEncountersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create an encounter
 */
export const postApiEncounters = <ThrowOnError extends boolean = false>(options?: Options<PostApiEncountersData, ThrowOnError>) => (options?.client ?? client).post<PostApiEncountersResponses, unknown, ThrowOnError>({
    url: '/api/encounters',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get encounter state
 */
export const getApiEncountersByEncounterIdState = <ThrowOnError extends boolean = false>(options: Options<GetApiEncountersByEncounterIdStateData, ThrowOnError>) => (options.client ?? client).get<GetApiEncountersByEncounterIdStateResponses, GetApiEncountersByEncounterIdStateErrors, ThrowOnError>({ url: '/api/encounters/{encounterId}/state', ...options });

/**
 * Add a combatant to an encounter
 */
export const postApiEncountersByEncounterIdCombatants = <ThrowOnError extends boolean = false>(options: Options<PostApiEncountersByEncounterIdCombatantsData, ThrowOnError>) => (options.client ?? client).post<PostApiEncountersByEncounterIdCombatantsResponses, unknown, ThrowOnError>({
    url: '/api/encounters/{encounterId}/combatants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
