// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3001' | (string & {});
};

export type Character = {
    characterId: string;
    name: string;
    level: number;
    characterClass: string;
    background: string;
    armorClass: number;
    initiative: number;
    speed: number;
    maxHp: number;
    strength: number;
    dexterity: number;
    constitution: number;
    intelligence: number;
    wisdom: number;
    charisma: number;
};

export type CreateCharacterRequest = {
    characterId: string;
    name: string;
    level: number;
    characterClass: string;
    background: string;
    armorClass: number;
    initiative: number;
    speed: number;
    maxHp: number;
    strength: number;
    dexterity: number;
    constitution: number;
    intelligence: number;
    wisdom: number;
    charisma: number;
};

export type Encounter = {
    id: string;
    name: string;
    status: 'setup' | 'running' | 'paused' | 'completed';
    roundNumber: number;
    activeTurnIndex?: number;
    version?: number;
    createdAt: string;
};

export type Combatant = {
    id: string;
    encounterId: string;
    kind: 'player' | 'enemy' | 'npc';
    displayName: string;
    initiative: number;
    initiativeOrder: number;
    currentHp: number;
    maxHp: number;
    armorClass: number | null;
    attackBonus: number | null;
    conditions: Array<string>;
    isDefeated: boolean;
};

export type EncounterSnapshot = {
    encounter: Encounter;
    combatants: Array<Combatant>;
};

export type CreateEncounterRequest = {
    name?: string;
};

export type AddCombatantRequest = {
    kind: 'player' | 'enemy' | 'npc';
    displayName: string;
    initiative: number;
    currentHp: number;
    maxHp: number;
    armorClass: number;
    attackBonus: number;
};

export type GetApiCharactersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/characters';
};

export type GetApiCharactersResponses = {
    /**
     * Character list.
     */
    200: Array<Character>;
};

export type GetApiCharactersResponse = GetApiCharactersResponses[keyof GetApiCharactersResponses];

export type PostApiCharactersData = {
    body: CreateCharacterRequest;
    path?: never;
    query?: never;
    url: '/api/characters';
};

export type PostApiCharactersResponses = {
    /**
     * Character created.
     */
    201: Character;
};

export type PostApiCharactersResponse = PostApiCharactersResponses[keyof PostApiCharactersResponses];

export type GetApiCharactersByCharacterIdData = {
    body?: never;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/api/characters/{characterId}';
};

export type GetApiCharactersByCharacterIdResponses = {
    /**
     * Character, if found.
     */
    200: Character;
};

export type GetApiCharactersByCharacterIdResponse = GetApiCharactersByCharacterIdResponses[keyof GetApiCharactersByCharacterIdResponses];

export type GetApiEncountersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/encounters';
};

export type GetApiEncountersResponses = {
    /**
     * Encounter list.
     */
    200: Array<Encounter>;
};

export type GetApiEncountersResponse = GetApiEncountersResponses[keyof GetApiEncountersResponses];

export type PostApiEncountersData = {
    body?: CreateEncounterRequest;
    path?: never;
    query?: never;
    url: '/api/encounters';
};

export type PostApiEncountersResponses = {
    /**
     * Encounter created.
     */
    201: Encounter;
};

export type PostApiEncountersResponse = PostApiEncountersResponses[keyof PostApiEncountersResponses];

export type GetApiEncountersByEncounterIdStateData = {
    body?: never;
    path: {
        encounterId: string;
    };
    query?: never;
    url: '/api/encounters/{encounterId}/state';
};

export type GetApiEncountersByEncounterIdStateErrors = {
    /**
     * Encounter was not found.
     */
    500: unknown;
};

export type GetApiEncountersByEncounterIdStateResponses = {
    /**
     * Encounter snapshot with combatants.
     */
    200: EncounterSnapshot;
};

export type GetApiEncountersByEncounterIdStateResponse = GetApiEncountersByEncounterIdStateResponses[keyof GetApiEncountersByEncounterIdStateResponses];

export type PostApiEncountersByEncounterIdCombatantsData = {
    body: AddCombatantRequest;
    path: {
        encounterId: string;
    };
    query?: never;
    url: '/api/encounters/{encounterId}/combatants';
};

export type PostApiEncountersByEncounterIdCombatantsResponses = {
    /**
     * Combatant added.
     */
    201: Combatant;
};

export type PostApiEncountersByEncounterIdCombatantsResponse = PostApiEncountersByEncounterIdCombatantsResponses[keyof PostApiEncountersByEncounterIdCombatantsResponses];
