// Creature class to create a creature object from json
// Is this a good pattern in typescript ¯\_(͡° ͜ʖ ͡°)_/¯

import { titleCase } from "../../utils/titleCase";
import type { Creature, Skills, Speed, NamedBlock } from "./CreatureTypes";

export class CreatureEntity {
  slug: string;
  desc: string;
  name: string;
  size: string;
  type: string;
  subType: string | null | undefined;
  group: string | null | undefined;
  alignment: string | null | undefined;
  armor_class: number;
  armor_desc: string | null | undefined;
  hit_points: number;
  hit_dice: string | null | undefined;
  speed: Speed;
  str: number;
  dex: number;
  con: number;
  int: number;
  wis: number;
  cha: number;
  str_save: number | null | undefined;
  dex_save: number | null | undefined;
  con_save: number | null | undefined;
  int_save: number | null | undefined;
  wis_save: number | null | undefined;
  cha_save: number | null | undefined;
  perception: number | null | undefined;
  skills: Skills;
  damage_vulns: string | null | undefined;
  damage_res: string | null | undefined;
  damage_immunities: string | null | undefined;
  cond_immunities: string | null | undefined;
  senses: string | null | undefined;
  languages: string | null | undefined;
  challenge_rating: string | null | undefined;
  cr: number | null | undefined;
  actions: Array<NamedBlock> | null | undefined;
  bonus_actions: Array<NamedBlock> | null | undefined;
  reactions: Array<NamedBlock> | null | undefined;
  legendary_desc: string | null | undefined;
  legendary_actions: Array<NamedBlock> | null | undefined;
  special_abilities: Array<NamedBlock> | null | undefined;
  spell_list: Array<String> | null | undefined;
  page_no: number | null | undefined;
  environments: Array<string> | null | undefined;
  img_main: string | null | undefined;
  document__slug: string | null | undefined;
  document__title: string | null | undefined;
  document__license_url: string | null | undefined;
  document__url: string | null | undefined;
  v2_converted_path: string | null | undefined;

  constructor(creature: Creature) {
    this.slug = creature.slug;
    this.desc = creature.desc;
    this.name = creature.name;
    this.size = creature.size;
    this.type = creature.type;
    this.subType = creature.subtype;
    this.group = creature.group;
    this.alignment = creature.alignment;
    this.armor_class = creature.armor_class;
    this.armor_desc = creature.armor_desc;
    this.hit_points = creature.hit_points;
    this.hit_dice = creature.hit_dice;
    this.speed = creature.speed;
    this.str = creature.strength;
    this.dex = creature.dexterity;
    this.con = creature.constitution;
    this.int = creature.intelligence;
    this.wis = creature.wisdom;
    this.cha = creature.charisma;
    this.str_save = creature.strength_save;
    this.dex_save = creature.dexterity_save;
    this.con_save = creature.constitution_save;
    this.int_save = creature.intelligence_save;
    this.wis_save = creature.wisdom_save;
    this.cha_save = creature.charisma_save;
    this.perception = creature.perception;
    this.skills = creature.skills;
    this.damage_vulns = creature.damage_vulnerabilities;
    this.damage_res = creature.damage_resistances;
    this.damage_immunities = creature.damage_immunities;
    this.cond_immunities = creature.condition_immunities;
    this.senses = creature.senses;
    this.languages = creature.languages;
    this.challenge_rating = creature.challenge_rating;
    this.cr = creature.cr;
    this.actions = creature.actions;
    this.bonus_actions = creature.bonus_actions;
    this.reactions = creature.reactions;
    this.legendary_desc = creature.legendary_desc;
    this.legendary_actions = creature.legendary_actions;
    this.special_abilities = creature.special_abilities;
    this.spell_list = creature.spell_list;
    this.page_no = creature.page_no;
    this.environments = creature.environments;
    this.img_main = creature.img_main;
    this.document__slug = creature.document__slug;
    this.document__title = creature.document__title;
    this.document__license_url = creature.document__license_url;
    this.document__url = creature.document__url;
    this.v2_converted_path = creature.v2_converted_path;
  }
}
